# Generated by Django 5.0.7 on 2025-09-29 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricoAsignacion',
            fields=[
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(verbose_name='Fecha')),
                ('history_change_reason', models.CharField(blank=True, max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'INSERCIÓN'), ('~', 'MODIFICACIÓN')], max_length=1, verbose_name='Operación')),
                ('fecha_asignacion', models.DateField()),
                ('estatus', models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo')], default='Activo', max_length=20)),
                ('motivo', models.TextField(blank=True, help_text='¿Motivo de desactivación de la asignación?', max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'asignacion',
                'verbose_name_plural': 'asignaciones',
                'db_table': 'public"."gestion_historicalasignacion',
                'managed': False,
            },
        ),
    ]
