# Generated by Django 5.0.7 on 2025-06-30 19:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=255)),
                ('cod_catalogo', models.CharField(max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
                'db_table': 'auxiliares"."categoria',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Marca',
                'verbose_name_plural': 'Marcas',
                'db_table': 'auxiliares"."marca',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origen', models.CharField(choices=[('V', 'V'), ('E', 'E')], max_length=1, verbose_name='Origen')),
                ('cedula', models.IntegerField(verbose_name='Cédula')),
                ('nombres_apellidos', models.CharField(max_length=255, verbose_name='Nombres/Apellidos')),
                ('cargo', models.CharField(max_length=100, verbose_name='cargo')),
            ],
            options={
                'verbose_name': 'Persona',
                'verbose_name_plural': 'Personas',
                'db_table': 'auxiliares"."persona',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Unidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=255)),
                ('tipo', models.CharField(choices=[('DG', 'Dirección General'), ('DL', 'Dirección de Línea'), ('D', 'División'), ('EA', 'Ente Adscrito')], max_length=50)),
            ],
            options={
                'verbose_name': 'Unidad',
                'verbose_name_plural': 'Unidades',
                'db_table': 'auxiliares"."unidad',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Modelo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=255)),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='auxiliares.marca')),
            ],
            options={
                'verbose_name': 'Modelo',
                'verbose_name_plural': 'Modelos',
                'db_table': 'auxiliares"."modelo',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Bien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caracteristicas', models.TextField(blank=True, null=True)),
                ('cod_bien', models.CharField(help_text='Código de bien Nacional', max_length=50, unique=True, verbose_name='codigo_de_bien')),
                ('tipo_uso', models.CharField(choices=[('Individual', 'Individual'), ('Colectivo', 'Colectivo')], max_length=50, verbose_name='tipo de uso')),
                ('valor_unitario', models.DecimalField(decimal_places=2, help_text='Valor unitario del bien', max_digits=10, verbose_name='valor unitario')),
                ('condicion', models.CharField(help_text='Condición del bien', max_length=50, verbose_name='condición')),
                ('estatus', models.CharField(choices=[('Operativo', 'Operativo'), ('Desincorporado', 'Desincorporado')], default='Activo', help_text='Estado del bien', max_length=20, verbose_name='estatus')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='auxiliares.categoria', verbose_name='Categoría')),
                ('modelo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='auxiliares.modelo')),
            ],
            options={
                'verbose_name': 'Bien',
                'verbose_name_plural': 'Bienes',
                'db_table': 'auxiliares"."bien',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Responsable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('persona', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='datos_persona', to='auxiliares.persona')),
            ],
            options={
                'verbose_name': 'Responsable',
                'verbose_name_plural': 'Responsables',
                'db_table': 'auxiliares"."responsable',
                'managed': True,
            },
        ),
    ]
