# Generated by Django 5.0.7 on 2025-09-03 03:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auxiliares', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='responsable',
            old_name='unidad',
            new_name='subdependencia',
        ),
        migrations.AddField(
            model_name='responsable',
            name='dependencia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dependencia', to='auxiliares.dependencia'),
        ),
    ]
