# Generated by Django 5.0.7 on 2025-10-21 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auxiliares', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estado',
            name='tipo',
            field=models.CharField(choices=[('Asignacion', 'Asignacion'), ('Bien', 'Bien'), ('Devolucion', 'Devolucion'), ('Personal', 'Personal')], max_length=100),
        ),
    ]
