# Generated by Django 5.2.6 on 2025-09-21 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auxiliares', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Motivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=255)),
                ('tipo', models.CharField(max_length=100)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Motivo',
                'verbose_name_plural': 'Motivos',
                'db_table': 'auxiliares"."motivo',
                'managed': True,
            },
        ),
    ]
