# Generated by Django 5.0.7 on 2025-07-17 18:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auxiliares', '0001_initial'),
        ('gestion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='unidad',
            name='director',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='gestion.director'),
        ),
        migrations.AddField(
            model_name='unidad',
            name='unidad_padre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sububicaciones', to='auxiliares.unidad'),
        ),
        migrations.AddField(
            model_name='responsable',
            name='unidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='unidad', to='auxiliares.unidad'),
        ),
    ]
