# Generated by Django 5.0.7 on 2025-10-21 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auxiliares', '0002_alter_estado_tipo'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoBien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Tipo de Bien',
                'verbose_name_plural': 'Tipos de Bienes',
                'db_table': 'catalogo_bienes"."tipo_bien',
            },
        ),
    ]
