# Generated by Django 5.0.7 on 2025-09-05 01:07

import django.db.models.deletion
import smart_selects.db_fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auxiliares', '0002_rename_unidad_responsable_subdependencia_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='descripcion',
            field=models.CharField(max_length=255, verbose_name='Categoría'),
        ),
        migrations.AlterField(
            model_name='subdependencia',
            name='dependencia',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='nombre', chained_model_field='nombre', on_delete=django.db.models.deletion.CASCADE, to='auxiliares.dependencia'),
        ),
    ]
