# Generated by Django 5.0.7 on 2026-01-23 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auxiliares', '0003_tipobien'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personal',
            name='estado',
        ),
        migrations.AlterModelOptions(
            name='color',
            options={'verbose_name': 'Color', 'verbose_name_plural': 'Colores'},
        ),
        migrations.AlterModelOptions(
            name='condicionbien',
            options={'verbose_name': 'Condicion de Bien', 'verbose_name_plural': 'Condiciones'},
        ),
        migrations.RemoveField(
            model_name='dependencia',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='subdependencia',
            name='descripcion',
        ),
    ]
