# Generated by Django 5.0.7 on 2025-09-05 01:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auxiliares', '0003_alter_categoria_descripcion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subdependencia',
            name='dependencia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subdependencias', to='auxiliares.dependencia', verbose_name='Dependencia a la que pertenece'),
        ),
    ]
