# Generated by Django 5.0.7 on 2026-01-23 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auxiliares', '0004_remove_personal_estado_alter_color_options_and_more'),
        ('bien', '0008_personal_alter_asignacion_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Personal',
        ),
    ]
