# Generated by Django 5.0.7 on 2025-06-30 19:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auxiliares', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asignacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_asignacion', models.DateField()),
                ('estatus', models.CharField(max_length=20)),
                ('observacion', models.TextField(max_length=50)),
                ('bien', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='auxiliares.bien')),
                ('responsable', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='auxiliares.responsable')),
                ('ubicacion', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='auxiliares.unidad')),
            ],
            options={
                'verbose_name': 'asignacion',
                'verbose_name_plural': 'asignaciones',
                'db_table': 'gestion"."asignacion',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resolucion', models.CharField(max_length=100, verbose_name='Resolución DM/N°')),
                ('fecha_resolucion', models.DateField(verbose_name='Fecha de la Resolución')),
                ('gaceta', models.CharField(max_length=100, verbose_name='Gaceta Oficial N°')),
                ('fecha_gaceta', models.DateField(verbose_name='Fecha de la Gaceta Oficial')),
                ('fecha_designacion', models.DateField(auto_now_add=True, verbose_name='Fecha de Designación')),
                ('persona', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='persona_info', to='auxiliares.persona')),
            ],
            options={
                'verbose_name': 'Director',
                'verbose_name_plural': 'Directores',
                'db_table': 'gestion"."director',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_bien', models.CharField(unique=True, verbose_name='N° de inventario del bien')),
                ('valor_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado', models.CharField(choices=[('Operativo', 'Operativo'), ('Prestado', 'Prestado'), ('Densicorporado', 'Densicorporado')], max_length=20)),
                ('tipo_uso', models.CharField(choices=[('Individual', 'Individual'), ('Colectivo', 'Colectivo')], max_length=255)),
                ('descripcion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='auxiliares.bien')),
                ('responsable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auxiliares.responsable')),
                ('ubicacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='auxiliares.unidad')),
            ],
            options={
                'verbose_name': 'inventario',
                'verbose_name_plural': 'inventario',
                'db_table': 'gestion"."inventario',
                'managed': True,
            },
        ),
    ]
