# Generated by Django 5.2.6 on 2025-09-20 23:10

import django.db.models.deletion
import django.utils.timezone
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auxiliares', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caracteristicas', models.TextField(blank=True, null=True)),
                ('cod_bien', models.CharField(help_text='Código de bien Nacional', max_length=50, unique=True, verbose_name='codigo de bien')),
                ('tipo_uso', models.CharField(choices=[('Individual', 'Individual'), ('Colectivo', 'Colectivo')], max_length=50, verbose_name='tipo de uso')),
                ('valor_unitario', models.DecimalField(decimal_places=2, help_text='Valor unitario del bien', max_digits=10, verbose_name='valor unitario')),
                ('condicion', models.CharField(choices=[('Nuevo', 'Nuevo'), ('Usado', 'Usado'), ('Deteriorado', 'Deteriorado'), ('Obsoleto', 'Obsoleto'), ('En reparación', 'En reparación')], default='Nuevo', help_text='Condición física del bien', max_length=50, verbose_name='condición')),
                ('estatus', models.CharField(choices=[('Disponible', 'Disponible'), ('Desincorporado', 'Desincorporado')], default='Disponible', help_text='Estado del bien', max_length=20, verbose_name='estatus')),
                ('fecha_adquisicion', models.DateField(blank=True, null=True, verbose_name='fecha de adqusición')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='auxiliares.categoria', verbose_name='Categoría')),
                ('modelo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='auxiliares.modelo')),
            ],
            options={
                'verbose_name': 'Bien',
                'verbose_name_plural': 'Bienes',
                'db_table': 'auxiliares"."bien',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Asignacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_asignacion', models.DateField()),
                ('estatus', models.CharField(choices=[('Activa', 'Activa'), ('Inactiva', 'Inactiva')], default='Activa', max_length=20)),
                ('motivo', models.TextField(blank=True, help_text='¿Motivo de desactivación de la asignación?', max_length=50, null=True)),
                ('dependencia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='auxiliares.dependencia')),
                ('responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='auxiliares.responsable')),
                ('subdependencia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='auxiliares.subdependencia')),
                ('bien', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='gestion.bien')),
            ],
            options={
                'verbose_name': 'asignacion',
                'verbose_name_plural': 'asignaciones',
                'db_table': 'gestion"."asignacion',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resolucion', models.CharField(max_length=100, verbose_name='Resolución DM/N°')),
                ('fecha_resolucion', models.DateField(verbose_name='Fecha de la Resolución')),
                ('gaceta', models.CharField(max_length=100, verbose_name='Gaceta Oficial N°')),
                ('fecha_gaceta', models.DateField(verbose_name='Fecha de la Gaceta Oficial')),
                ('fecha_designacion', models.DateField(auto_now_add=True, verbose_name='Fecha de Designación')),
                ('persona', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='persona_info', to='auxiliares.persona')),
            ],
            options={
                'verbose_name': 'Director',
                'verbose_name_plural': 'Directores',
                'db_table': 'gestion"."director',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='HistoricalAsignacion',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('fecha_asignacion', models.DateField()),
                ('estatus', models.CharField(choices=[('Activa', 'Activa'), ('Inactiva', 'Inactiva')], default='Activa', max_length=20)),
                ('motivo', models.TextField(blank=True, help_text='¿Motivo de desactivación de la asignación?', max_length=50, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('bien', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='gestion.bien')),
                ('dependencia', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='auxiliares.dependencia')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('responsable', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='auxiliares.responsable')),
                ('subdependencia', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='auxiliares.subdependencia')),
            ],
            options={
                'verbose_name': 'historical asignacion',
                'verbose_name_plural': 'historical asignaciones',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Prestamo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField(default=django.utils.timezone.now)),
                ('fecha_final', models.DateField()),
                ('encargado', models.CharField(max_length=150)),
                ('motivo', models.TextField()),
                ('fecha_devolucion', models.DateField(blank=True, null=True)),
                ('estado_bien_devolucion', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('EN_PRESTAMO', 'En préstamo'), ('DEVUELTO', 'Devuelto'), ('RETRASO', 'Retraso de préstamo')], default='EN_PRESTAMO', max_length=20)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('bien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prestamos', to='gestion.bien')),
                ('ubicacion_departamento', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='prestamos', to='auxiliares.dependencia')),
            ],
            options={
                'verbose_name': 'préstamo',
                'verbose_name_plural': 'préstamos',
                'db_table': 'gestion"."prestamo',
                'ordering': ['-creado'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='DetallePrestamo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condicion_devolucion', models.CharField(blank=True, choices=[('BUENO', 'En buen estado'), ('DAÑADO', 'Dañado'), ('PERDIDO', 'Perdido')], max_length=20, null=True)),
                ('bien', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detalles_prestamo', to='gestion.bien')),
                ('prestamo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='gestion.prestamo')),
            ],
            options={
                'verbose_name': 'detalle de préstamo',
                'verbose_name_plural': 'detalles de préstamos',
                'db_table': 'gestion"."detalle_prestamo',
                'ordering': ['bien__cod_bien'],
                'managed': True,
                'unique_together': {('prestamo', 'bien')},
            },
        ),
    ]
