# Generated by Django 5.2.6 on 2025-09-20 23:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prestamo',
            name='bien',
        ),
    ]
