# Generated by Django 5.0.7 on 2025-09-05 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bien',
            name='estatus',
            field=models.CharField(choices=[('Disponible', 'Disponible'), ('Desincorporado', 'Desincorporado')], default='Disponible', help_text='Estado del bien', max_length=20, verbose_name='estatus'),
        ),
    ]
