# Generated by Django 5.0.7 on 2025-09-29 17:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auxiliares', '0001_initial'),
        ('gestion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResponsablePrestamo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prestamo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responsables', to='gestion.prestamo')),
                ('responsable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responsables_prestamo', to='auxiliares.responsable')),
            ],
            options={
                'verbose_name': 'responsable de préstamo',
                'verbose_name_plural': 'responsables de préstamos',
                'db_table': 'gestion"."responsable_prestamo',
                'managed': True,
            },
        ),
    ]
