# Generated by Django 5.2.6 on 2025-09-21 00:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_remove_prestamo_bien'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prestamo',
            name='estado_bien_devolucion',
        ),
    ]
