# Generated by Django 5.0.7 on 2025-07-01 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_alter_asignacion_estatus_alter_asignacion_ubicacion_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='asignacion',
            old_name='observacion',
            new_name='motivo',
        ),
    ]
