# Generated by Django 5.0.7 on 2025-09-05 01:41

import django.db.models.deletion
import smart_selects.db_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auxiliares', '0004_alter_subdependencia_dependencia'),
        ('gestion', '0002_alter_bien_estatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asignacion',
            name='subdependencia',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='dependencia', chained_model_field='dependencia', default=1, on_delete=django.db.models.deletion.CASCADE, to='auxiliares.subdependencia'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='historicalasignacion',
            name='subdependencia',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, blank=True, chained_field='dependencia', chained_model_field='dependencia', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='auxiliares.subdependencia'),
        ),
    ]
