# Generated by Django 5.0.7 on 2025-07-01 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0003_rename_observacion_asignacion_motivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asignacion',
            name='motivo',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
    ]
