# Generated by Django 5.2.6 on 2025-09-21 00:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auxiliares', '0002_motivo'),
        ('gestion', '0003_remove_prestamo_estado_bien_devolucion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalleprestamo',
            name='condicion_devolucion',
            field=models.CharField(blank=True, choices=[('BUENO', 'En buen estado'), ('DAÑADO', 'Dañado'), ('PERDIDO', 'Perdido')], max_length=20, null=True, verbose_name='Condición de retorno'),
        ),
        migrations.AlterField(
            model_name='prestamo',
            name='motivo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='prestamos', to='auxiliares.motivo'),
        ),
    ]
