# Generated by Django 5.2.6 on 2025-09-21 20:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0004_alter_detalleprestamo_condicion_devolucion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalleprestamo',
            name='bien',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detalles', to='gestion.bien'),
        ),
    ]
