# Generated by Django 5.0.7 on 2025-07-02 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auxiliares', '0002_initial'),
        ('gestion', '0004_alter_asignacion_motivo'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='asignacion',
            constraint=models.UniqueConstraint(condition=models.Q(('estatus', 'Activo')), fields=('bien', 'responsable'), name='uniq_bien_responsable_activo'),
        ),
    ]
