# Generated by Django 5.0.7 on 2025-07-16 16:17

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auxiliares', '0002_initial'),
        ('gestion', '0005_asignacion_uniq_bien_responsable_activo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalAsignacion',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('fecha_asignacion', models.DateField()),
                ('estatus', models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo')], default='Activo', max_length=20)),
                ('motivo', models.TextField(blank=True, help_text='¿Motivo de desactivación de la asignación?', max_length=50, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical asignacion',
                'verbose_name_plural': 'historical asignaciones',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.RemoveConstraint(
            model_name='asignacion',
            name='uniq_bien_responsable_activo',
        ),
        migrations.AlterField(
            model_name='asignacion',
            name='motivo',
            field=models.TextField(blank=True, help_text='¿Motivo de desactivación de la asignación?', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='historicalasignacion',
            name='bien',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='auxiliares.bien'),
        ),
        migrations.AddField(
            model_name='historicalasignacion',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalasignacion',
            name='responsable',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='auxiliares.responsable'),
        ),
        migrations.AddField(
            model_name='historicalasignacion',
            name='ubicacion',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='auxiliares.unidad'),
        ),
    ]
