# Generated by Django 5.0.7 on 2025-10-21 18:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auxiliares', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asignacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_asignacion', models.DateField()),
                ('observaciones', models.TextField()),
                ('estatus', models.CharField(max_length=20)),
                ('dependencia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='auxiliares.dependencia')),
                ('subdependencia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='auxiliares.subdependencia')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='auxiliares.personal')),
            ],
            options={
                'db_table': 'bien"."asignacion',
            },
        ),
        migrations.CreateModel(
            name='Bien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_bien', models.CharField(max_length=50)),
                ('serial', models.CharField(max_length=100)),
                ('observaciones', models.TextField()),
                ('fecha_adquisicion', models.DateField()),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='auxiliares.color')),
                ('condicion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='auxiliares.condicionbien')),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='auxiliares.estado')),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='auxiliares.marca')),
                ('modelo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='auxiliares.modelo')),
            ],
            options={
                'verbose_name': 'Bien',
                'verbose_name_plural': 'Bienes',
                'db_table': 'bien"."bien',
            },
        ),
        migrations.CreateModel(
            name='DetalleAsignacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('fecha_retorno', models.DateField(blank=True, null=True)),
                ('asignacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bien.asignacion')),
                ('bien', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bien.bien')),
                ('estatus', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='auxiliares.estado')),
            ],
            options={
                'db_table': 'bien"."detalle_asignacion',
            },
        ),
        migrations.CreateModel(
            name='Devolucion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_devolucion', models.DateField()),
                ('observaciones', models.TextField()),
                ('asignacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bien.asignacion')),
            ],
            options={
                'db_table': 'bien"."devolucion',
            },
        ),
        migrations.CreateModel(
            name='DetalleDevolucion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observaciones', models.TextField()),
                ('fecha_retorno', models.DateField()),
                ('condicion_retorno', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='auxiliares.condicionbien')),
                ('detalle_asignacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bien.detalleasignacion')),
                ('devolucion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bien.devolucion')),
            ],
            options={
                'db_table': 'bien"."detalle_devolucion',
            },
        ),
    ]
