# Generated by Django 5.0.7 on 2026-02-06 15:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auxiliares', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asignacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nro_asignacion', models.CharField(editable=False, max_length=20, unique=True)),
                ('fecha_asignacion', models.DateField(auto_now_add=True)),
                ('dependencia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='auxiliares.dependencia')),
                ('estatus', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='auxiliares.estado')),
                ('subdependencia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='auxiliares.subdependencia')),
            ],
            options={
                'verbose_name': 'Asignacion',
                'verbose_name_plural': 'Asignaciones',
                'db_table': 'bien"."asignacion',
            },
        ),
        migrations.CreateModel(
            name='Bien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_bien', models.CharField(max_length=50, unique=True)),
                ('serial', models.CharField(blank=True, max_length=100, null=True)),
                ('valor_unitario', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('fecha_adquisicion', models.DateField(blank=True, null=True)),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='auxiliares.color')),
                ('condicion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='auxiliares.condicionbien')),
                ('estado', models.ForeignKey(default=3, on_delete=django.db.models.deletion.PROTECT, to='auxiliares.estado')),
                ('marca', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='auxiliares.marca')),
                ('modelo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='auxiliares.modelo')),
                ('tipo_bien', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='auxiliares.tipobien')),
            ],
            options={
                'verbose_name': 'Bien',
                'verbose_name_plural': 'Bienes',
                'db_table': 'bien"."bien',
            },
        ),
        migrations.CreateModel(
            name='DetalleAsignacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_retorno', models.DateField(blank=True, null=True)),
                ('devuelto', models.BooleanField(default=False)),
                ('asignacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bien.asignacion')),
                ('bien', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bien.bien')),
            ],
            options={
                'db_table': 'bien"."detalle_asignacion',
            },
        ),
        migrations.CreateModel(
            name='Devolucion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_devolucion', models.DateField()),
                ('observaciones', models.TextField()),
                ('asignacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bien.asignacion')),
            ],
            options={
                'verbose_name': 'Devolucion',
                'verbose_name_plural': 'Devoluciones',
                'db_table': 'bien"."devolucion',
            },
        ),
        migrations.CreateModel(
            name='DetalleDevolucion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observaciones', models.TextField()),
                ('fecha_retorno', models.DateField()),
                ('condicion_retorno', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='auxiliares.condicionbien')),
                ('detalle_asignacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bien.detalleasignacion')),
                ('devolucion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bien.devolucion')),
            ],
            options={
                'db_table': 'bien"."detalle_devolucion',
            },
        ),
        migrations.CreateModel(
            name='Personal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origen', models.CharField(choices=[('V', 'V'), ('E', 'E')], max_length=1)),
                ('cedula', models.CharField(max_length=15)),
                ('nombres_apellidos', models.CharField(max_length=100, verbose_name='Nombre/Apellido')),
                ('cargo', models.CharField(max_length=100)),
                ('departamento', models.CharField(max_length=100)),
                ('activo', models.BooleanField(default=True)),
                ('subdependencia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='auxiliares.subdependencia')),
            ],
            options={
                'verbose_name': 'Personal',
                'verbose_name_plural': 'Personal',
                'db_table': 'auxiliares"."personal',
            },
        ),
        migrations.AddField(
            model_name='asignacion',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bien.personal'),
        ),
    ]
