# Generated by Django 5.0.7 on 2026-02-06 17:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auxiliares', '0002_dependencia_codigo'),
        ('bien', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personal',
            name='departamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='auxiliares.dependencia', to_field='codigo'),
        ),
    ]
