# Generated by Django 5.0.7 on 2025-10-21 18:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auxiliares', '0002_alter_estado_tipo'),
        ('bien', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asignacion',
            name='estatus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='auxiliares.estado'),
        ),
    ]
