# Generated by Django 5.0.7 on 2025-10-21 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bien', '0002_alter_asignacion_estatus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detalleasignacion',
            name='cantidad',
        ),
    ]
