# Generated by Django 5.0.7 on 2025-10-21 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bien', '0003_remove_detalleasignacion_cantidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asignacion',
            name='fecha_asignacion',
            field=models.DateField(auto_now_add=True),
        ),
    ]
