# Generated by Django 5.0.7 on 2025-10-21 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bien', '0004_alter_asignacion_fecha_asignacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='asignacion',
            name='nro_asignacion',
            field=models.CharField(default=1, editable=False, max_length=20, unique=True),
            preserve_default=False,
        ),
    ]
