# Generated by Django 5.0.7 on 2025-10-21 19:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auxiliares', '0003_tipobien'),
        ('bien', '0005_asignacion_nro_asignacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='bien',
            name='tipo_bien',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='auxiliares.tipobien'),
            preserve_default=False,
        ),
    ]
