# Generated by Django 5.0.7 on 2025-10-21 19:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auxiliares', '0003_tipobien'),
        ('bien', '0006_bien_tipo_bien'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bien',
            name='tipo_bien',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='auxiliares.tipobien'),
        ),
    ]
