# Generated by Django 5.0.7 on 2026-01-23 15:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auxiliares', '0004_remove_personal_estado_alter_color_options_and_more'),
        ('bien', '0007_alter_bien_tipo_bien'),
    ]

    operations = [
        migrations.CreateModel(
            name='Personal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origen', models.CharField(max_length=1)),
                ('cedula', models.CharField(max_length=15)),
                ('nombres_apellidos', models.CharField(max_length=100)),
                ('cargo', models.CharField(max_length=100)),
                ('departamento', models.CharField(max_length=100)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Personal',
                'verbose_name_plural': 'Personal',
                'db_table': 'auxiliares"."personal',
            },
        ),
       
        migrations.AlterModelOptions(
            name='devolucion',
            options={'verbose_name': 'Devolucion', 'verbose_name_plural': 'Devoluciones'},
        ),
        migrations.RemoveField(
            model_name='bien',
            name='observaciones',
        ),
       
        migrations.AddField(
            model_name='bien',
            name='valor_unitario',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
       
        migrations.AlterField(
            model_name='bien',
            name='fecha_adquisicion',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bien',
            name='marca',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='auxiliares.marca'),
        ),
        migrations.AlterField(
            model_name='bien',
            name='modelo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='auxiliares.modelo'),
        ),
        migrations.AlterField(
            model_name='asignacion',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bien.personal'),
        ),
    ]
